# escape=`

# ----------------------------------------------------------------------
FROM container-registry-zurich.oracle.com/database/enterprise:19.3.0.0

ARG orahome=/opt/oracle/product/19c/dbhome_1
COPY extproc.ora $orahome/hs/admin/extproc.ora

COPY lib/Pro/3.0/Oracle/Linux64/libst_shapelib.so /opt/oracle/esrilib/libst_shapelib.so